import './contracts/validation.test.js';
import './cli/cli.test.js';
import './conversion/showui-trace.test.js';
import './task/data-paths.test.js';
import './task/task-core.test.js';
import './task/execution.test.js';
import './executors/keyboard-type-action.test.js';
import './executors/yaml-runner.test.js';
import './skill/package.test.js';
